// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Modules',
      items: [
        'Modules/Admin-tools',
        'Modules/Afk-system',
        'Modules/Ai-chat-channel',
        'Modules/imagine',
        'Modules/Anonymous-chat',
        'Modules/Anti-ghostping',
        {
          type: 'category',
          label: 'Applications',
          link: {
            type: 'generated-index',
            title: 'Applications',
            description: 'With this module, you can make applications to your server easier. Once you set up this module, people can apply for roles (e.g., Moderator, etc.) that you configure. Because this module has two configuration pages, you’ll need to choose one of the pages below:',
            slug: 'Modules/Applications',
          },
          items: [
            'Modules/Applications/Application-Categories',
            'Modules/Applications/Configuration',
          ]
        },
        {
          type: 'category',
          label: 'Auto-Message-Delete',
          link: {
            type: 'generated-index',
            title: 'Auto-Message-Delete',
            description: 'With this module, the bot automatically deletes messages in a Discord channel that you’ve set up. This helps keep the channel clean and prevents it from being cluttered with too many messages.',
            slug: 'Modules/Auto-Message-Delete'
          },
          items: [
            'Modules/Auto-Message-Delete/Text-Channels',
            'Modules/Auto-Message-Delete/Voice-Channels'
          ]
        },
        {
          type: 'category',
          label: 'Automatic Messages',
          link: {
            type: 'generated-index',
            title: 'Automatic Messages',
            description: 'With this module, you can set up automatic messages that the bot sends at a time you configure. There are several types of automatic messages you can set up: Hourly Basic, Daily Basic, and Cronjobs. Cronjobs is the advanced page used to configure more complex automatic messages.',
            slug: 'Modules/Automatic-Messages',
          },
          items: [
            'Modules/Automatic-Messages/Hourly-basic',
            'Modules/Automatic-Messages/Daily-basic',
            'Modules/Automatic-Messages/Cronjob',
          ]
        },
        'Modules/Automatic-publishing',
        {
          type: 'category',
          label: 'Automatic Reactions',
          link: {
            type: 'generated-index',
            title: 'Automatic Reactions',
            description: 'With this module, you can setup diffrent types of things that the bot can automaticly react to, Channels, Mentions, Roles, Authors and Categories, we will explain everything here.',
            slug: 'Modules/Automatic-Reactions',
          },
          items: [
            'Modules/Automatic-reactions/Configuration',
            'Modules/Automatic-reactions/Replies',
          ]
        },
        'Modules/Automatic-thread-creation',
        'Modules/Betterstatus',
        'Modules/Birthday',
        'Modules/Channel-stats',
        {
          type: 'category',
          label: 'Color me',
          link: {
            type: 'generated-index',
            title: 'Color me',
            description: 'With this Module, you can reward your Users with Custom Roles that they can personalize if they boost your Server. only they can create and edit their own Color Role.',
            slug: 'Modules/Color-me',
          },
          items: [
            'Modules/Color-me/Configuration',
            'Modules/Color-me/Messages'
          ]
        },
        'Modules/Connect-four',
        {
          type: 'category',
          label: 'Count-Game',
          link: {
            type: 'generated-index',
            title: 'Count-Game',
            description: 'With this module you can set up a Counting Game in your Discord server. A Counting Game is a fun community activity where users take turns counting starting from 1 and continuing upwards one number at a time. You can also decide how strict the game should be, for example you can enable a rule that restarts the count if someone posts the wrong number. Everything is customizable so you can adjust it to fit your servers style. In addition you can create Milestones with custom messages and even assign roles as rewards. This helps make the game more exciting and motivates users to participate more often.',
            slug: 'Modules/Count-game',
          },
          items: [
            'Modules/Count-game/Configuration',
            'Modules/Count-game/Milestones',
          ],
        },
        'Modules/Duel',
        {
          type: 'category',
          label: 'Economy',
          link: {
            type: 'generated-index',
            title: 'Economy',
            description: 'With this module, you can set up a fun and engaging economy system in your Discord server. Users can earn virtual currency through various activities, such as participating in games, completing tasks, or receiving rewards from other members. The economy module helps foster a sense of community and encourages user interaction by providing incentives for participation.',
            slug: 'Modules/Economy',
          },
          items: [
            'Modules/Economy/Configuration',
            'Modules/Economy/Messages',
          ]
        },
        {
          type: 'category',
          label: 'Emoji-Quiz',
          link: {
            type: 'generated-index',
            title: 'Emoji-Quiz',
            description: 'With this module, you can set up an Emoji Quiz game in your Discord server. In this game, the bot sends a series of emojis that represent a word, phrase, or concept, and users have to guess what it is based on the emojis provided. The Emoji Quiz is a fun and interactive way to engage your community and encourage participation. If you also want to suggest a quiz question, please visit https://scnx.app/user/crowdsource/emoji-quiz and submit your idea there!',
            slug: 'Modules/Emoji-quiz',
          },
          items: [
            'Modules/Emoji-quiz/Configuration',
            'Modules/Emoji-quiz/Custom-game-questions',
          ]
        },
        'Modules/Guess-the-flag',
        'Modules/Forum-support',
        'Modules/Fun-commands',
        {
          type: 'category',
          label: 'Giveaways',
          link: {
            type: 'generated-index',
            title: 'Giveaways',
            description: 'With this module, you can easily create and manage giveaways in your Discord server. Giveaways are a great way to engage your community and reward your members with prizes. You can customize various aspects of the giveaway, such as the duration, number of winners, and eligibility criteria. The bot will handle the entry process, randomly select winners, and announce them in the designated channel.',
            slug: 'Modules/Giveaways',
          },
          items: [
            'Modules/Giveaways/Configuration',
            'Modules/Giveaways/Messages',
          ]
        },
        {
          type: 'category',
          label: 'Guess the Number',
          link: {
            type: 'generated-index',
            title: 'Guess the Number',
            description: 'With this module, you can set up a fun "Guess the Number" game in your Discord server. In this game, the bot (or the Admins) randomly selects a number within a specified range, and users have to guess what that number is. The bot provides feedback on whether the guess is too high, too low, or correct (you can configure if it should show the High or Low hints). This interactive game encourages user participation and adds an element of excitement to your server.',
            slug: 'Modules/Guess-the-number',
          },
          items: [
            'Modules/Guess-the-number/Configuration',
            'Modules/Guess-the-number/Gamechannel-mode',
          ]
        }
      ]
    }
  ],
};

export default sidebars;
