// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Modules',
      items: [
        'Modules/Admin-tools',
        'Modules/Afk-system',
        'Modules/Ai-chat-channel',
        'Modules/imagine',
        'Modules/Anonymous-chat'
      ]
    }
  ],
};

export default sidebars;
